name: Build and Release LaTeX PDF

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t latex-compiler .

      - name: Compile LaTeX document
        run: |
          docker run --rm \
            -v "${{ github.workspace }}/src:/src" \
            latex-compiler \
            /bin/bash -c "pdflatex -output-directory /src /src/Satzung.tex"

      - name: Upload compiled PDF artifact
        uses: actions/upload-artifact@v3
        with:
          name: Satzung.pdf
          path: src/Satzung.pdf

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Download compiled PDF artifact
        uses: actions/download-artifact@v3
        with:
          name: Satzung.pdf
          path: Satzung.pdf

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: "v${{ github.run_number }}"
          release_name: "Satzung PDF Release"
          body: "Compiled PDF of Satzung.tex"
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload PDF to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: Satzung.pdf
          asset_name: Satzung.pdf
          asset_content_type: application/pdf
